repeat_rate=25
repeat_delay=600
numlockon=0
xkb_rules_layout=dk

# Keybindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# reload config
bind=SUPER,r,reload_config

# Noctalia
bind=SUPER,Return,spawn,qs -c noctalia-shell ipc call launcher toggle
bind=SUPER,s,spawn,qs -c noctalia-shell ipc call settings toggle
bind=SUPER+SHIFT,l,spawn,qs -c noctalia-shell ipc call sessionMenu toggle

# apps
bind=SUPER,t,spawn,ghostty

# switch window focus
bind=SUPER,Tab,focusstack,next
bind=SUPER,h,focusdir,left
bind=SUPER,l,focusdir,right
bind=SUPER,k,focusdir,up
bind=SUPER,j,focusdir,down

# swap window
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

# switch window status
bind=SUPER,g,toggleglobal,
bind=SUPER,o,toggleoverview,
bind=ALT,backslash,togglefloating,
bind=ALT,a,togglemaximizescreen,
bind=ALT,f,togglefullscreen,
bind=ALT+SHIFT,f,togglefakefullscreen,
bind=SUPER,i,minimized
bind=SUPER,z,toggle_scratchpad
bind=SUPER,q,killclient

# switch layout
bind=SUPER,n,switch_layout
bind=SUPER+CTRL,s,setlayout,scroller
bind=SUPER+CTRL,c,setlayout,center_tile

# tag switch
bind=SUPER+SHIFT,k,viewtoleft,0
bind=SUPER+SHIFT,j,viewtoright,0
bind=CTRL+SUPER,k,tagtoleft,0
bind=CTRL+SUPER,j,tagtoright,0
